/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T -o src/components/model/model.tsx public/objects/pokeball/scene.gltf 
Files: public/objects/pokeball/scene.gltf [5.57KB] > /home/marceloek/github.com/marceloek/CG-2019.2N-T1/src/components/model/scene-transformed.glb [436.71KB] (-7740%)
Author: Jesús Orgaz (https://sketchfab.com/chusorgaz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/poke-ball-pokemon-pokeball-c266163bd310411bac727783e4c79c4a
Title: Poké Ball - Pokemon Pokeball
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    poke_up_Pokeball_0: THREE.Mesh
  }
  materials: {
    Pokeball: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
// >

export function Pokeball(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/pokeball.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.poke_up_Pokeball_0.geometry}
        material={materials.Pokeball}
        position={[-4.038, 65.35, -0.264]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/glb/pokeball.glb')
