/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T -o src/components/model/model.tsx public/objects/rock/2/scene.gltf 
Files: public/objects/rock/2/scene.gltf [19.72KB] > /home/marceloek/github.com/marceloek/CG-2019.2N-T1/src/components/model/scene-transformed.glb [1.37MB] (-6853%)
Author: 3DMaesen (https://sketchfab.com/bumstrum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/3279b8d99fe244059c40a66e8aa39590
Title: Portal
*/

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    portalbase_portal_0: THREE.Mesh
  }
  materials: {
    portal: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
// >

export function Portal(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/portal.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.portalbase_portal_0.geometry}
        material={materials.portal}
        position={[5.204, -65.047, 0]}
      />
    </group>
  )
}

useGLTF.preload('/glb/portal.glb')
