/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T -o src/components/model/model.tsx public/objects/tree/5/scene.gltf 
Files: public/objects/tree/5/scene.gltf [14.34KB] > /home/marceloek/github.com/marceloek/CG-2019.2N-T1/src/components/model/scene-transformed.glb [739.72KB] (-5058%)
Author: BaptisteBerard (https://sketchfab.com/BaptisteBerard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/ea5e6ed7f9d6445ba69589d503e8cebf
Title: Tree
*/

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    yggrassil_02_bark_0: THREE.Mesh
    yggrassil_02_leaves_0: THREE.Mesh
    yggrassil_02_cap_0: THREE.Mesh
    yggrassil_02_Default_Material_0: THREE.Mesh
  }
  materials: {
    bark: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Default_Material: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
// >

export function TreeFive(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/tree-five.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.yggrassil_02_bark_0.geometry}
        material={materials.bark}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.846}
      />
      <mesh
        geometry={nodes.yggrassil_02_leaves_0.geometry}
        material={materials.leaves}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.846}
      />
      <mesh
        geometry={nodes.yggrassil_02_cap_0.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.846}
      />
      <mesh
        geometry={nodes.yggrassil_02_Default_Material_0.geometry}
        material={materials.Default_Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.846}
      />
    </group>
  )
}

useGLTF.preload('/glb/tree-five.glb')
