/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t -T -o src/components/model/model.tsx public/objects/tree/3/scene.gltf 
Files: public/objects/tree/3/scene.gltf [7.6KB] > /home/marceloek/github.com/marceloek/CG-2019.2N-T1/src/components/model/scene-transformed.glb [451.83KB] (-5845%)
Author: Harri Jones (https://sketchfab.com/HarriJones23)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/models/41fa3210e50944eaa489c148e5e2ccc7
Title: Fur Tree
*/

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pPlane145_Branch_0: THREE.Mesh
    pPlane145_lambert5_0: THREE.Mesh
  }
  materials: {
    Branch: THREE.MeshStandardMaterial
    lambert5: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
// >

export function TreeThree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/tree-three.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pPlane145_Branch_0.geometry}
        material={materials.Branch}
        position={[0, -19.09, 0]}
      />
      <mesh
        geometry={nodes.pPlane145_lambert5_0.geometry}
        material={materials.lambert5}
        position={[0, -19.09, 0]}
      />
    </group>
  )
}

useGLTF.preload('/glb/tree-three.glb')
